name: Deploy Resources

: # on:
: #  workflow_dispatch: # Allows you to run the workflow manually
: #  schedule:
: #    - cron: '0 9 * * 1-5' # Runs at 8 AM UTC, Monday to Friday

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: $NGAZURESECRET

    - name: Deploy Bicep template
      run: |
        az deployment group create --name NG-securitycopilot --resource-group rgSecurityCopilot --template-file ./main.bicep --parameters ./main.biceppara
